### ISSUE TITLE
Not downloading videos and post with multiple media

### ISSUE THREAD

**Issue by djcrawleravp** [shyd/docker-instagram-scraper#2]
Any parameter I'm missing?

I created a bash

#! /bin/bash

docker run -it --rm \
    -v /home/djcrawleravp/storage/Downloads/Instagram:/download \
    -v /home/djcrawleravp/.config/appdata/instagram-scrapper/ig_args.txt:/ig_args.txt \
    -v /home/djcrawleravp/.config/appdata/instagram-scrapper/ig_users.txt:/ig_users.txt \
    shyd/instagram-scraper

**Comment by djcrawleravp** [comment]
my ig_args.txt 

-t image, video, story, story-image, story-video
--retry-forever
--latest

**Comment by shyd** [comment]
Project is not available anymore. Sorry!
